version: 2.1

orbs:
  node: circleci/node@4.0.0

jobs:
  test:
    machine:
      image: 'circleci/classic:latest'
    parameters:
      browser:
        type: string
        default: chrome
    steps:
      - checkout
      #- node/install:
      #    install-yarn: true
      #    lts: true
      #- run:
      #    name: Build souce code & compile test project
      #    command: docker-compose run --rm gondola.builder
       #   working_directory: 
      - run:
          name: run all tests
          command: docker-compose run --rm gondola.tester
          environment:
            BROWSER: << parameters.browser >>
      - store_test_results:
          path: results/
      - store_artifacts:
          path: results/
          destination: results

workflows:
  test:
    jobs:
      - test:
          context: Gondola License
          matrix:
            parameters:
              browser:
                - chrome
                - firefox
